# Generated by Django 3.2.9 on 2022-02-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
    ]
